#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PORT="${PORT:-3333}"
NPM_BIN="${NPM_BIN:-$(command -v npm || true)}"
DATABASE_URL_VALUE="${DATABASE_URL:-postgres://deepstock:deepstock@127.0.0.1:15432/deepstock}"
API_TOKEN_VALUE="${API_TOKEN:-${DEEPSTOCK_API_TOKEN:-dev-token}}"
DEEPSTOCK_API_TOKEN_VALUE="${DEEPSTOCK_API_TOKEN:-${API_TOKEN_VALUE}}"
LLM_PROVIDER_VALUE="${LLM_PROVIDER:-glm}"
LOCK_MODE_VALUE="${LOCK_MODE:-memory}"
GLM_API_KEY_VALUE="${GLM_API_KEY:-}"
GLM_BASE_URL_VALUE="${GLM_BASE_URL:-}"
GLM_MODEL_VALUE="${GLM_MODEL:-}"
GLM_TEMPERATURE_VALUE="${GLM_TEMPERATURE:-}"
GEMINI_API_KEY_VALUE="${GEMINI_API_KEY:-}"
GEMINI_BASE_URL_VALUE="${GEMINI_BASE_URL:-}"
GEMINI_MODEL_VALUE="${GEMINI_MODEL:-}"
GEMINI_TEMPERATURE_VALUE="${GEMINI_TEMPERATURE:-}"
LLM_MODEL_VALUE="${LLM_MODEL:-}"
OPENAI_API_KEY_VALUE="${OPENAI_API_KEY:-}"
OPENAI_BASE_URL_VALUE="${OPENAI_BASE_URL:-}"
OPENAI_TEMPERATURE_VALUE="${OPENAI_TEMPERATURE:-}"
RUN_MAX_SECONDS_VALUE="${RUN_MAX_SECONDS:-}"
MIN_SECONDS_BETWEEN_RUNS_VALUE="${MIN_SECONDS_BETWEEN_RUNS:-}"
GATHER_MAX_ITEMS_PER_SOURCE_VALUE="${GATHER_MAX_ITEMS_PER_SOURCE:-}"
SCORE_TOP_N_VALUE="${SCORE_TOP_N:-}"
DECIDE_TOP_N_VALUE="${DECIDE_TOP_N:-}"
LLM_MAX_SIGNALS_PER_RUN_VALUE="${LLM_MAX_SIGNALS_PER_RUN:-}"
LLM_MAX_CALLS_PER_RUN_VALUE="${LLM_MAX_CALLS_PER_RUN:-}"
LLM_MAX_TOKENS_PER_CALL_VALUE="${LLM_MAX_TOKENS_PER_CALL:-}"
DEFAULT_MARKET_SCOPE_VALUE="${DEFAULT_MARKET_SCOPE:-}"
DEFAULT_STRATEGY_KEY_VALUE="${DEFAULT_STRATEGY_KEY:-}"
KR_MARKET_ENABLED_VALUE="${KR_MARKET_ENABLED:-}"
DART_API_KEY_VALUE="${DART_API_KEY:-}"
NAVER_ENABLED_VALUE="${NAVER_ENABLED:-}"
DART_ENABLED_VALUE="${DART_ENABLED:-}"
KR_COMMUNITY_ENABLED_VALUE="${KR_COMMUNITY_ENABLED:-}"
KR_NEWS_ENABLED_VALUE="${KR_NEWS_ENABLED:-}"
US_GATHER_MAX_ITEMS_PER_SOURCE_VALUE="${US_GATHER_MAX_ITEMS_PER_SOURCE:-}"
US_DECIDE_TOP_N_VALUE="${US_DECIDE_TOP_N:-}"
US_LLM_MAX_SIGNALS_PER_RUN_VALUE="${US_LLM_MAX_SIGNALS_PER_RUN:-}"
US_LLM_MAX_CALLS_PER_RUN_VALUE="${US_LLM_MAX_CALLS_PER_RUN:-}"
US_LLM_MAX_TOKENS_PER_CALL_VALUE="${US_LLM_MAX_TOKENS_PER_CALL:-}"
KR_GATHER_MAX_ITEMS_PER_SOURCE_VALUE="${KR_GATHER_MAX_ITEMS_PER_SOURCE:-}"
KR_DECIDE_TOP_N_VALUE="${KR_DECIDE_TOP_N:-}"
KR_LLM_MAX_SIGNALS_PER_RUN_VALUE="${KR_LLM_MAX_SIGNALS_PER_RUN:-}"
KR_LLM_MAX_CALLS_PER_RUN_VALUE="${KR_LLM_MAX_CALLS_PER_RUN:-}"
KR_LLM_MAX_TOKENS_PER_CALL_VALUE="${KR_LLM_MAX_TOKENS_PER_CALL:-}"
ALL_GATHER_MAX_ITEMS_PER_SOURCE_VALUE="${ALL_GATHER_MAX_ITEMS_PER_SOURCE:-}"
ALL_DECIDE_TOP_N_VALUE="${ALL_DECIDE_TOP_N:-}"
ALL_LLM_MAX_SIGNALS_PER_RUN_VALUE="${ALL_LLM_MAX_SIGNALS_PER_RUN:-}"
ALL_LLM_MAX_CALLS_PER_RUN_VALUE="${ALL_LLM_MAX_CALLS_PER_RUN:-}"
ALL_LLM_MAX_TOKENS_PER_CALL_VALUE="${ALL_LLM_MAX_TOKENS_PER_CALL:-}"

PID_FILE="${PID_FILE:-/tmp/deepstock-dev.pid}"
LOG_FILE="${LOG_FILE:-/tmp/deepstock-dev.log}"
AGENT_LABEL="${AGENT_LABEL:-com.stock_analysis_event.dev}"
PLIST_FILE="${PLIST_FILE:-$HOME/Library/LaunchAgents/${AGENT_LABEL}.plist}"

is_listening() {
  lsof -nP -iTCP:"${PORT}" -sTCP:LISTEN >/dev/null 2>&1
}

supervisor_running() {
  [[ -f "${PID_FILE}" ]] && kill -0 "$(cat "${PID_FILE}")" >/dev/null 2>&1
}

if is_listening; then
  echo "Already listening on :${PORT}"
  exit 0
fi

if [[ "${USE_LAUNCHCTL:-false}" == "true" ]] && [[ "$(uname -s)" == "Darwin" ]] && command -v launchctl >/dev/null 2>&1; then
  mkdir -p "$(dirname "${LOG_FILE}")" "$HOME/Library/LaunchAgents"

  cat >"${PLIST_FILE}" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${AGENT_LABEL}</string>
  <key>ProgramArguments</key>
    <array>
    <string>/bin/bash</string>
    <string>-lc</string>
    <string>cd '${ROOT_DIR}' &amp;&amp; export NEXT_TELEMETRY_DISABLED=1 NEXT_DIST_DIR='.next-dev' PORT='${PORT}' DATABASE_URL='${DATABASE_URL_VALUE}' API_TOKEN='${API_TOKEN_VALUE}' DEEPSTOCK_API_TOKEN='${DEEPSTOCK_API_TOKEN_VALUE}' LLM_PROVIDER='${LLM_PROVIDER_VALUE}' LOCK_MODE='${LOCK_MODE_VALUE}' GLM_API_KEY='${GLM_API_KEY_VALUE}' GLM_BASE_URL='${GLM_BASE_URL_VALUE}' GLM_MODEL='${GLM_MODEL_VALUE}' GLM_TEMPERATURE='${GLM_TEMPERATURE_VALUE}' GEMINI_API_KEY='${GEMINI_API_KEY_VALUE}' GEMINI_BASE_URL='${GEMINI_BASE_URL_VALUE}' GEMINI_MODEL='${GEMINI_MODEL_VALUE}' GEMINI_TEMPERATURE='${GEMINI_TEMPERATURE_VALUE}' LLM_MODEL='${LLM_MODEL_VALUE}' OPENAI_API_KEY='${OPENAI_API_KEY_VALUE}' OPENAI_BASE_URL='${OPENAI_BASE_URL_VALUE}' OPENAI_TEMPERATURE='${OPENAI_TEMPERATURE_VALUE}' RUN_MAX_SECONDS='${RUN_MAX_SECONDS_VALUE}' MIN_SECONDS_BETWEEN_RUNS='${MIN_SECONDS_BETWEEN_RUNS_VALUE}' GATHER_MAX_ITEMS_PER_SOURCE='${GATHER_MAX_ITEMS_PER_SOURCE_VALUE}' SCORE_TOP_N='${SCORE_TOP_N_VALUE}' DECIDE_TOP_N='${DECIDE_TOP_N_VALUE}' LLM_MAX_SIGNALS_PER_RUN='${LLM_MAX_SIGNALS_PER_RUN_VALUE}' LLM_MAX_CALLS_PER_RUN='${LLM_MAX_CALLS_PER_RUN_VALUE}' LLM_MAX_TOKENS_PER_CALL='${LLM_MAX_TOKENS_PER_CALL_VALUE}' DEFAULT_MARKET_SCOPE='${DEFAULT_MARKET_SCOPE_VALUE}' DEFAULT_STRATEGY_KEY='${DEFAULT_STRATEGY_KEY_VALUE}' KR_MARKET_ENABLED='${KR_MARKET_ENABLED_VALUE}' DART_API_KEY='${DART_API_KEY_VALUE}' NAVER_ENABLED='${NAVER_ENABLED_VALUE}' DART_ENABLED='${DART_ENABLED_VALUE}' KR_COMMUNITY_ENABLED='${KR_COMMUNITY_ENABLED_VALUE}' KR_NEWS_ENABLED='${KR_NEWS_ENABLED_VALUE}' US_GATHER_MAX_ITEMS_PER_SOURCE='${US_GATHER_MAX_ITEMS_PER_SOURCE_VALUE}' US_DECIDE_TOP_N='${US_DECIDE_TOP_N_VALUE}' US_LLM_MAX_SIGNALS_PER_RUN='${US_LLM_MAX_SIGNALS_PER_RUN_VALUE}' US_LLM_MAX_CALLS_PER_RUN='${US_LLM_MAX_CALLS_PER_RUN_VALUE}' US_LLM_MAX_TOKENS_PER_CALL='${US_LLM_MAX_TOKENS_PER_CALL_VALUE}' KR_GATHER_MAX_ITEMS_PER_SOURCE='${KR_GATHER_MAX_ITEMS_PER_SOURCE_VALUE}' KR_DECIDE_TOP_N='${KR_DECIDE_TOP_N_VALUE}' KR_LLM_MAX_SIGNALS_PER_RUN='${KR_LLM_MAX_SIGNALS_PER_RUN_VALUE}' KR_LLM_MAX_CALLS_PER_RUN='${KR_LLM_MAX_CALLS_PER_RUN_VALUE}' KR_LLM_MAX_TOKENS_PER_CALL='${KR_LLM_MAX_TOKENS_PER_CALL_VALUE}' ALL_GATHER_MAX_ITEMS_PER_SOURCE='${ALL_GATHER_MAX_ITEMS_PER_SOURCE_VALUE}' ALL_DECIDE_TOP_N='${ALL_DECIDE_TOP_N_VALUE}' ALL_LLM_MAX_SIGNALS_PER_RUN='${ALL_LLM_MAX_SIGNALS_PER_RUN_VALUE}' ALL_LLM_MAX_CALLS_PER_RUN='${ALL_LLM_MAX_CALLS_PER_RUN_VALUE}' ALL_LLM_MAX_TOKENS_PER_CALL='${ALL_LLM_MAX_TOKENS_PER_CALL_VALUE}' &amp;&amp; exec '${NPM_BIN}' run -s dev:3333:all</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${ROOT_DIR}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${LOG_FILE}</string>
  <key>StandardErrorPath</key>
  <string>${LOG_FILE}</string>
</dict>
</plist>
EOF

  uid="$(id -u)"
  launchctl bootout "gui/${uid}/${AGENT_LABEL}" >/dev/null 2>&1 || true
  launchctl bootstrap "gui/${uid}" "${PLIST_FILE}" >/dev/null 2>&1 || {
    launchctl load -w "${PLIST_FILE}" >/dev/null 2>&1 || true
  }
  launchctl kickstart -k "gui/${uid}/${AGENT_LABEL}" >/dev/null 2>&1 || true

  echo "Started launch agent: ${AGENT_LABEL}"
  echo "Logs: ${LOG_FILE}"
  exit 0
fi

if supervisor_running; then
  echo "Supervisor is running (pid=$(cat "${PID_FILE}")) but :${PORT} is not listening yet."
  echo "Tail logs: tail -f ${LOG_FILE}"
  exit 0
fi

mkdir -p "$(dirname "${LOG_FILE}")" || true

nohup env \
  NEXT_TELEMETRY_DISABLED=1 \
  NEXT_DIST_DIR=.next-dev \
  PORT="${PORT}" \
  DATABASE_URL="${DATABASE_URL_VALUE}" \
  API_TOKEN="${API_TOKEN_VALUE}" \
  DEEPSTOCK_API_TOKEN="${DEEPSTOCK_API_TOKEN_VALUE}" \
  LLM_PROVIDER="${LLM_PROVIDER_VALUE}" \
  LOCK_MODE="${LOCK_MODE_VALUE}" \
  GLM_API_KEY="${GLM_API_KEY_VALUE}" \
  GLM_BASE_URL="${GLM_BASE_URL_VALUE}" \
  GLM_MODEL="${GLM_MODEL_VALUE}" \
  GLM_TEMPERATURE="${GLM_TEMPERATURE_VALUE}" \
  GEMINI_API_KEY="${GEMINI_API_KEY_VALUE}" \
  GEMINI_BASE_URL="${GEMINI_BASE_URL_VALUE}" \
  GEMINI_MODEL="${GEMINI_MODEL_VALUE}" \
  GEMINI_TEMPERATURE="${GEMINI_TEMPERATURE_VALUE}" \
  LLM_MODEL="${LLM_MODEL_VALUE}" \
  OPENAI_API_KEY="${OPENAI_API_KEY_VALUE}" \
  OPENAI_BASE_URL="${OPENAI_BASE_URL_VALUE}" \
  OPENAI_TEMPERATURE="${OPENAI_TEMPERATURE_VALUE}" \
  RUN_MAX_SECONDS="${RUN_MAX_SECONDS_VALUE}" \
  MIN_SECONDS_BETWEEN_RUNS="${MIN_SECONDS_BETWEEN_RUNS_VALUE}" \
  GATHER_MAX_ITEMS_PER_SOURCE="${GATHER_MAX_ITEMS_PER_SOURCE_VALUE}" \
  SCORE_TOP_N="${SCORE_TOP_N_VALUE}" \
  DECIDE_TOP_N="${DECIDE_TOP_N_VALUE}" \
  LLM_MAX_SIGNALS_PER_RUN="${LLM_MAX_SIGNALS_PER_RUN_VALUE}" \
  LLM_MAX_CALLS_PER_RUN="${LLM_MAX_CALLS_PER_RUN_VALUE}" \
  LLM_MAX_TOKENS_PER_CALL="${LLM_MAX_TOKENS_PER_CALL_VALUE}" \
  DEFAULT_MARKET_SCOPE="${DEFAULT_MARKET_SCOPE_VALUE}" \
  DEFAULT_STRATEGY_KEY="${DEFAULT_STRATEGY_KEY_VALUE}" \
  KR_MARKET_ENABLED="${KR_MARKET_ENABLED_VALUE}" \
  DART_API_KEY="${DART_API_KEY_VALUE}" \
  NAVER_ENABLED="${NAVER_ENABLED_VALUE}" \
  DART_ENABLED="${DART_ENABLED_VALUE}" \
  KR_COMMUNITY_ENABLED="${KR_COMMUNITY_ENABLED_VALUE}" \
  KR_NEWS_ENABLED="${KR_NEWS_ENABLED_VALUE}" \
  US_GATHER_MAX_ITEMS_PER_SOURCE="${US_GATHER_MAX_ITEMS_PER_SOURCE_VALUE}" \
  US_DECIDE_TOP_N="${US_DECIDE_TOP_N_VALUE}" \
  US_LLM_MAX_SIGNALS_PER_RUN="${US_LLM_MAX_SIGNALS_PER_RUN_VALUE}" \
  US_LLM_MAX_CALLS_PER_RUN="${US_LLM_MAX_CALLS_PER_RUN_VALUE}" \
  US_LLM_MAX_TOKENS_PER_CALL="${US_LLM_MAX_TOKENS_PER_CALL_VALUE}" \
  KR_GATHER_MAX_ITEMS_PER_SOURCE="${KR_GATHER_MAX_ITEMS_PER_SOURCE_VALUE}" \
  KR_DECIDE_TOP_N="${KR_DECIDE_TOP_N_VALUE}" \
  KR_LLM_MAX_SIGNALS_PER_RUN="${KR_LLM_MAX_SIGNALS_PER_RUN_VALUE}" \
  KR_LLM_MAX_CALLS_PER_RUN="${KR_LLM_MAX_CALLS_PER_RUN_VALUE}" \
  KR_LLM_MAX_TOKENS_PER_CALL="${KR_LLM_MAX_TOKENS_PER_CALL_VALUE}" \
  ALL_GATHER_MAX_ITEMS_PER_SOURCE="${ALL_GATHER_MAX_ITEMS_PER_SOURCE_VALUE}" \
  ALL_DECIDE_TOP_N="${ALL_DECIDE_TOP_N_VALUE}" \
  ALL_LLM_MAX_SIGNALS_PER_RUN="${ALL_LLM_MAX_SIGNALS_PER_RUN_VALUE}" \
  ALL_LLM_MAX_CALLS_PER_RUN="${ALL_LLM_MAX_CALLS_PER_RUN_VALUE}" \
  ALL_LLM_MAX_TOKENS_PER_CALL="${ALL_LLM_MAX_TOKENS_PER_CALL_VALUE}" \
  "${NPM_BIN}" run -s dev:3333:all >"${LOG_FILE}" 2>&1 < /dev/null &

echo $! >"${PID_FILE}"

echo "Started dev daemon pid=$(cat "${PID_FILE}")"
echo "Logs: ${LOG_FILE}"
